### ISSUE TITLE
Frequently High CPU Usage

### ISSUE THREAD

**Issue by LokeYourLord** [7gxycn08/WSA-Tray-Helper#1]
**Bug Description:**
Having the program just sitting idly by (which is pretty much what it is supposed to do anyways), will cause it to frequently spike higher in CPU usage % than many other active programs (even beyond 10% under some circumstances). This is odd, because all this program should do is start and stop WSA and nothing else.

**Expected Behaviour:**
The program shouldn't consume more than a few per mille (a fraction of a %) in terms of CPU usage (roughly 0.1% maybe).

**Additional Information:**
OS: Windows 11 Pro 22H2
CPU: AMD Ryzen 7 5700X @4.4GHz
GPU: NVIDIA RTX 3070
RAM: ADATA G60D 32GB DDR4 @3200MHz

**Screenshots:**
![image](https://user-images.githubusercontent.com/5807595/221091733-486b1df6-4391-48b1-b166-d2c172b512b8.png)

**Comment by 7gxycn08** [comment]
On my PC It spikes to only 0.7% usage every 5 seconds that's due to the icon updating function.

I think it has to do with the checking process.
You can try increasing the timer on line 55 `timer.start(5000)`
If we use for example 30000 It will check if WSA is running once every 30 seconds and update the icon theoretically that would lower the usage. It might be related to the PyQt library though.

If you want I can make a hotfix for you with a higher timer value so you can test it out or you can simple compile one yourself.

**Comment by LokeYourLord** [comment]
I suppose that might work, can try by increasing the timer. If you could compile the hotfix for me I'd appreciate that, not at my Computer at the moment to compile it myself :)

**Comment by 7gxycn08** [comment]
[https://github.com/7gxycn08/WSA-Tray-Helper/releases/tag/v1.1](url)

Here you go test this out and tell me how it goes.

If the usage is still not fixed I might have to replace psutil library and use a different method to check if WSA Is running.

**Comment by 7gxycn08** [comment]
If you don't want to test the hotfix you can skip it altogether and use the new version which removes psutil completely and uses a much more efficient method to check If WSA Is running.

[https://github.com/7gxycn08/WSA-Tray-Helper/releases/tag/v1.2](url)

**Comment by LokeYourLord** [comment]
> If you don't want to test the hotfix you can skip it altogether and use the new version which removes psutil completely and uses a much more efficient method to check If WSA Is running.
> 
> [https://github.com/7gxycn08/WSA-Tray-Helper/releases/tag/v1.2](url) 

Alright sounds great, I'll give it a try when I'm up~

**Comment by LokeYourLord** [comment]
Seems fixed, has been sitting at pretty much 0% all the time:
![image](https://user-images.githubusercontent.com/5807595/221332489-ddabdccd-dd4e-4e34-a272-954aabdb7289.png)
