### ISSUE TITLE
Backup problems - 2nd issue

### ISSUE THREAD

**Issue by pdimu** [7gxycn08/WSA-Tray-Helper#3]
i was looking for making backup for wsa, and after very-much-search, i found this. everything is fine, but you misspelled the location for wsa to do backup:  

> Backup Error: [WinError 3] The system cannot find the path specified: 'C: **\\** Users\
\User **\\** AppData **\\** Local **\\** Packages\
\MicrosoftCorporationll.WindowsSubsystemForAndroid_8wekyb3d8bbwe\
LocalCache'

(M↓ is stupid today, i wanted to bold the "\\" from path, but it took me just one "\" ; but you can see the bold ones and correct them)
also, the username is taken as the Microsoft account name, but i have a different one, so that would be the second problem (i'll rename the user folder and see if it accepts it, but the path may be incorrect bcs of "\\")

**Comment by okgamr** [comment]
i can't rename the user folder, so the problem may be at the path: **the username and the "\ \" **

**Comment by okgamr** [comment]
maybe i can edit the path name from the py source, but i'm not very experienced in py, so i'd need someone's help

**Comment by 7gxycn08** [comment]
os.getlogin() is a built in python function that returns the username of the pc your logged into it does not return the microsoft account details specifically.
The path name is correct it works normally for me here is the complete path name which gets backup up.

`C:\Users\UserName\AppData\Local\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache`

On my PC the path is MicrosoftCorporationII with double capital ii
On yours is MicrosoftCorporation11 with double ones 

Can you share your windows build? number tried on multiple windows 11 systems and the path is always MicrosoftCorporationII with double ii.

Anyways I can fix that for you will make a new release that addresses the path change.

**Comment by okgamr** [comment]
no, my path is C:\Users\User\AppData\Local\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache , maybe the ocr has taken it wrong

my windows build is Win11 22H2 OS 22621.2715 - the latest

i remention that the program takes the username from the Microsoft Account, not the actual folder (whose name is different from the MS Acc name at me)

**Comment by okgamr** [comment]
> os.getlogin() is a built in python function that returns the username of the pc your logged into it does not return the microsoft account details specifically. The path name is correct it works normally for me here is the complete path name which gets backup up.
> 
> `C:\Users\UserName\AppData\Local\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache`
> 
> On my PC the path is MicrosoftCorporationII with double capital ii On yours is MicrosoftCorporation11 with double ones
> 
> Can you share your windows build? number tried on multiple windows 11 systems and the path is always MicrosoftCorporationII with double ii.
> 
> Anyways I can fix that for you will make a new release that addresses the path change.

sorry, now i've that you said 'username of the pc'. it's the same as the name of my MS Acc and they're both different from my User folder

**Comment by 7gxycn08** [comment]
> > os.getlogin() is a built in python function that returns the username of the pc your logged into it does not return the microsoft account details specifically. The path name is correct it works normally for me here is the complete path name which gets backup up.
> > `C:\Users\UserName\AppData\Local\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalCache`
> > On my PC the path is MicrosoftCorporationII with double capital ii On yours is MicrosoftCorporation11 with double ones
> > Can you share your windows build? number tried on multiple windows 11 systems and the path is always MicrosoftCorporationII with double ii.
> > Anyways I can fix that for you will make a new release that addresses the path change.
> 
> sorry, now i've that you said 'username of the pc'. it's the same as the name of my MS Acc and they're both different from my User folder

How is your user name different i need a proper example so i can debug.

Try running this python code 

```
import os

print(os.getlogin())

```

check to see if the printed output is the correct username which is placed in the folder path on your system.
Or does your wsa path is installed for a different user?

**Comment by okgamr** [comment]
i assure you, idk to use python (just if you guide me). the way i got just 'User' in my user folder is bcs i logged with MS just after i installed Windows. pretty interesting isn't it?

**Comment by 7gxycn08** [comment]
> i assure you, idk to use python (just if you guide me). the way i got just 'User' in my user folder is bcs i logged with MS just after i installed Windows. pretty interesting isn't it?
So let me get this straight your path starts with `C:\Users\User\AppData` It says User and not the computers username which is returned by os.getlogin() if so this must be windows bug.

Anyways i have a solution for you however it's not elegant you will have to manually add the full path to the LocalCache folder in an ini file and it will back it up automatically. Otherwise you need to install python and run this code and see what gets printed 
```
import os

print(os.getlogin())
```
1. Download python from https://www.python.org/
2. Create a text file and place the code in it.
3. Rename the text file to myfile.py
4. Open a command prompt and type python myfile.py

It will print the result username for you in console window.

**Comment by okgamr** [comment]
Ok, i'll do it, but everything tomorrow

2024-02-21 20:27 GMT+02:00, Andrew ***@***.***>:

**Comment by pdimu** [comment]
And yeah, the user folder is just 'User', but the user name is (just
as example) 'Green Frvr'. But i'll see what i get with python tomorrow

**Comment by 7gxycn08** [comment]
> And yeah, the user folder is just 'User', but the user name is (just as example) 'Green Frvr'. But i'll see what i get with python tomorrow 2024-02-21 21:03 GMT+02:00, Dimi P ***@***.***>:
> […](#)
> Ok, i'll do it, but everything tomorrow 2024-02-21 20:27 GMT+02:00, Andrew ***@***.***>: >> i assure you, idk to use python (just if you guide me). the way i got >> just >> 'User' in my user folder is bcs i logged with MS just after i installed >> Windows. pretty interesting isn't it? > So let me get this straight your path starts with `C:\Users\User\AppData` > It > says User and not the computers username which is returned by > os.getlogin() > if so this must be windows bug. > > Anyways i have a solution for you however it's not elegant you will have > to > manually add the full path to the LocalCache folder in an ini file and it > will back it up automatically. Otherwise you need to install python and > run > this code and see what gets printed > ``` > import os > > print(os.getlogin()) > ``` > 1. Download python from https://www.python.org/ > 2. Create a text file and place the code in it. > 3. Rename the text file to myfile.py > 4. Open a command prompt and type python myfile.py > > It will print the result username for you in console window. > > -- > Reply to this email directly or view it on GitHub: > [#3 (comment)](https://github.com/7gxycn08/WSA-Tray-Helper/issues/3#issuecomment-1957636711) > You are receiving this because you authored the thread. > > Message ID: ***@***.***>

ok will wait for your reply.

**Comment by 7gxycn08** [comment]
Solution Implemented.
https://github.com/7gxycn08/WSA-Tray-Helper/releases/tag/v1.0.1.2

**Comment by okgamr** [comment]
i've reviewed the releases tab and i tried the latest. but now idk where is my backup. some info, please?

**Comment by okgamr** [comment]
anyway, the folder selection for both backup & restore don't seem to be there

**Comment by 7gxycn08** [comment]
> i've reviewed the releases tab and i tried the latest. but now idk where is my backup. some info, please?

C:\Program Files (x86)\WSA-Tray-Helper\Backup

**Comment by pdimu** [comment]
oh ok thx
